name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install Frontend Dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Create Mock Environment File
      run: |
        cd frontend
        cat > .env << EOF
        VITE_API_BASE_URL=https://api-demo.aisteth.com
        VITE_APP_MODE=demo
        EOF
    
    - name: Build React Frontend
      run: |
        cd frontend
        npm run build
    
    - name: Create 404.html for SPA routing
      run: |
        cp frontend/dist/index.html frontend/dist/404.html
    
    - name: Add custom domain file (if needed)
      run: |
        echo "aisteth.pages.dev" > frontend/dist/CNAME || true
    
    - name: Setup Pages
      uses: actions/configure-pages@v4
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: 'frontend/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
